import './globals.css'
import type { Metadata } from 'next'
import Providers from "./providers"
import ThemeSwitcher from "./ThemeSwitcher"

export const metadata: Metadata = {
  title: 'News App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  )
}
